image:
  name: alpine/helm:3.1.2
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  HELM_EXPERIMENTAL_OCI: 1

test:
  script:
    - helm version
    - helm registry login -p ${CI_REGISTRY_PASSWORD} -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
    - helm chart save src/default-data/ingress ${CI_REGISTRY_IMAGE}/ingress:${CI_COMMIT_TAG}
    - helm chart list
    - helm chart push ${CI_REGISTRY_IMAGE}/ingress:${CI_COMMIT_TAG}