include:
  - component: $CI_SERVER_FQDN/components/opentofu/full-pipeline@~latest
    inputs:
      # The version must currently be specified explicitly as an input,
      # to find the correctly associated images. # This can be removed
      # once https://gitlab.com/gitlab-org/gitlab/-/issues/438275 is solved.
      version: latest
      opentofu_version: 1.7.1
      state_name: production

stages: [validate, test, build, deploy, cleanup]

vault ping:
  image:
    name: hashicorp/vault:latest
    entrypoint:
        - '/usr/bin/env'
        - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: validate
  script:
    - echo "Check status of $VAULT_ADDR"
    - |
      until vault status
      do
        echo "Vault returned error or sealed"
        sleep 5
      done
  rules:
    - if: '$VAULT_ADDR'
      when: always

fmt:
  allow_failure: false

plan:
  id_tokens:
    GITOPS_DEMO_VAULT_JWT:
      aud: "GITOPS-DEMO"
  extends: [.secrets, .opentofu:plan]

apply:
  extends: [.secrets, .opentofu:apply]
  id_tokens:
    GITOPS_DEMO_VAULT_JWT:
      aud: "GITOPS-DEMO"

destroy:
  extends: [.secrets, .opentofu:destroy]
  needs: []
  id_tokens:
    GITOPS_DEMO_VAULT_JWT:
      aud: "GITOPS-DEMO"

