include:
  - template: Terraform.latest.gitlab-ci.yml

variables:
  TF_IN_AUTOMATION: "true"
  TF_STATE_NAME: default
  TF_CACHE_KEY: default

vault ping:
  image:
    name: hashicorp/vault:latest
    entrypoint:
        - '/usr/bin/env'
        - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: .pre
  script:
    - echo "Check status of $VAULT_ADDR"
    - |
      until vault status
      do
        echo "Vault returned error or sealed"
        sleep 5
      done
  rules:
    - if: '$VAULT_ADDR'
      when: always

fmt:
  allow_failure: false

validate:
  extends: .secrets